### ISSUE TITLE
Сollapse and decrease block size

### ISSUE THREAD

**Issue by rsashka** [AllJavi/spoiler-block-obsidian#1]
Required plugin! 
Is it possible to make it collapse and decrease in size, and not just hide the text in the block?
Otherwise, the whole point of the spoiler is lost, since the size of the block occupied by it remains unchanged.

**Comment by rsashka** [comment]
Block hiding is already implemented in the editor

**Comment by d9k** [comment]
You can make [custom CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) to limit block height:

```
.block-language-spoiler-block {
  overflow: hidden;
}

.block-language-spoiler-block .spoiler {
  max-height: 80px;
}
```
