### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by d9k** [AllJavi/spoiler-block-obsidian#2]
Spoiler-block technically is a code block but whitespace at the beginning of the lines are ignored.

As a workaround you can use [custom CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets):

```
.block-language-spoiler-block {
  font-size: var(--font-ui-smaller);
}

.block-language-spoiler-block .spoiler,
.block-language-spoiler-block .spoiler-show {
  white-space: pre;
}
```

**Comment by AllJavi** [comment]
I think the `white-space: pre;` doesn't fix any significant problem and instead it creates a new one. If you apply that snippet you make the block to overflow horizontally.

Now:
![imagen](https://github.com/AllJavi/spoiler-block-obsidian/assets/49349604/d264e3d2-2629-4128-b3cd-52e254ad9eb8)

With the snippet:
![imagen](https://github.com/AllJavi/spoiler-block-obsidian/assets/49349604/51934f7e-0981-4796-9c87-b5728f670e19)
